blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("post.urls", namespace="post")),
    path("comment/", include("comment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from . import views

app_name = "comment"
urlpatterns = [path("send/", views.send, name="send")]

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("categories/", views.category_list, name="categories_list"),
    path("categories/<slug:slug>/", views.category_posts, name="category_posts"),
    path("categories/<str:category>/<slug:slug>/", views.detail, name="detail"),
    path("categories/<str:category>/<slug:slug>/edit/", views.edit, name="edit"),
    path("categories/<str:category>/<slug:slug>/delete/", views.delete, name="delete"),

    path("like/", views.like, name="like"),
    path("new_post/", views.new_post, name="new_post"),
]

comment/models.py
from django.db import models
from django.contrib.auth.models import User
from post.models import Post

# Create your models here.


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_comments"
    )
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_comments"
    )
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.post, self.body[:15]}"

comment/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.models import User
from post.models import Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'textarea is-small ta'})
        }
        labels = {
            'body': ''
        }
    def save(self, commit: bool, user:User, post:Post):
        comment: Comment =  super().save(commit=False)
        comment.user = user
        comment.post = post

        if commit:
            comment.save()
        return Comment

comment/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponse, JsonResponse
from .forms import CommentForm
from post.models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def send(request: HttpRequest):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get("post_id")
            post = get_object_or_404(Post.available_posts, id=int(post_id))
            form.save(commit=True, user=request.user, post=post)
            return redirect(post.get_absolute_url())
    else:
        form = CommentForm()

templates/partials/categories_box.html
{% load theme %}
<div class="panel {{user|theme}}">
    <p class="panel-heading ">
        Categories
    </p>
    
    {% for category in categories %}
        <a href="{% url 'post:category_posts' category.slug %}" class="panel-block">
            <p>{{category.title}}</p>
        </a>
    {% endfor %}
    
</div>

templates/partials/comment.html
{% load full_name %}
<li class="comment">
    <div class="author">
        {% if comment.user.profile.photo %}
            <img src="comment.user.profile.photo.url" class="author-img" alt="{{comment.user|fullname}}">
        {% else %}
            <div style="font-size:35px; margin-right:30px"><span class="icon"><i class="fa-solid fa-user"></i></span> </div>
        {% endif %}
            <h4 class="title is-4">{{comment.user|fullname}}</h4>
    </div>
    <hr>
    <p>{{comment.body|linebreaks}}</p>
</li>

templates/partials/comment_form.html
{% comment %} <form class="field" method="POST" id="commentForm" data-url="{% url 'post:leave_comment' %}">
    {% csrf_token %}
    <input type="hidden" name="post_id" value="{{post.id}}" id="post_id">
    <div class="control block">
        {{form}}
    </div>
    <div class="control block">
        <button type="submit" class="button is-light" id="commentBtn">Send</button>
    </div>
</form> {% endcomment %}

templates/partials/detail_content.html
{% load theme full_name %}
{% if post.banner %}<dive class="image block"><img src="{{post.banner.url}}" alt="{{post.title}}"></dive>{% endif %}
<h1 class="title is-1 block">{{post.title}}</h1>
<div class="block"><small>{{post.created}}</small></div>
<p class="block">{{post.body|safe}}</p>
<div class="block">Tags : <small>{{post.tags}}</small></div>
<hr>
<div>
    <div class="block ah">
        <div class="author">
            {% if post.user.profile.photo %}
                <img src="{{post.user.profile.photo.url}}" class="author-img" alt="{{post.user|fullname}}">
            {% else %}
                <div style="font-size:35px; margin-right:30px"><span class="icon"><i class="fa-solid fa-user"></i></span> </div>
            {% endif %}
            <h4 class="title is-4"><a href="#">{{post.user|fullname}}</a></h4>
        </div> 
        <div class="block like">
            <form class="like-btn" method="post" id="likeForm" data-url="{% url 'post:like' %}"  >
                <input type="hidden" name="post_id" value="{{post.id}}"/>
                {% csrf_token %}
                <button type="submit" class="button"><span id="likeBtn"
                    style='color:{% if action == 'like' %}black {% else %}red{% endif %}'
                    ><i class="fa-solid fa-heart"></i></span></button>
                <p id="likes">{{post.likes}}</p>
            </form>
            <div>
                <button type="button" class="button"><span class="icon"><i class="fa-solid fa-share"></i></span></button>
            </div>
            <div>
                <button type="button" class="button"><span class="icon"><i class="fa-solid fa-copy"></i></span></button>
            </div>
        </div>
    </div>
</div>

templates/partials/my_post_card.html
{% load static %}
<div class="ccard card">
    <div class="cc-img"><img src="{% if post.banner %}{{post.banner.url}}{% else %}{% static 'no_image.PNG' %}{% endif %}" alt="{{post.title}}"></div>
    <div class="card-content">
        <h4 class="title is-4">
            {{post.title}}
        </h4>
        <div class="field has-addons">
            <a href="{% url 'post:edit' post.category.title post.slug %}" class="button is-light is-success is-small">Edit</a> 
            <a href="{% url 'post:delete' post.category.title post.slug %}" class="button is-light is-danger is-small">Delete</a> 
            <p class="button is-small is-light is-light">Like{{post.likes|pluralize}} {{post.likes}}</p>
            <a href="{{post.get_absolute_url}}" class="button is-light is-warning is-small">see more</a>
        </div>
    </div>
</div>

templates/partials/paginator.html
<!-- pagination -->
<nav class="pagination is-rounded" role="navigation" aria-label="pagination">

    <a class="pagination-previous" {% if posts.has_previous %} href="/?page={{posts.previous_page_number}}" {% else %}disabled{% endif %}>Previous</a>

    <a class="pagination-next" {% if posts.has_next %} href="/?page={{posts.next_page_number}}" {% else %}disabled{% endif %}>Next page</a>


    <ul class="pagination-list">
        {% for page in posts.paginator.page_range %}
            <li>
                <a href="/?page={{page}}" class="pagination-link {% if posts.number == page %}is-current{% endif %}" aria-label="Goto page 1">
                    {{page}}
                </a>
            </li>
        {% endfor %}
        
    </ul>
</nav>

templates/partials/tags_box.html
    {% load theme %}
    <div class="panel {{user|theme}}">
        <p class="panel-heading">
            Tags
        </p>
        
        {% for tag in tags %}
            <a href="#" class="button is-small is-rounded" style="margin:5px">
                <p>{{tag.name}}</p>
            </a>
        {% endfor %}
        
    </div>

templates/partials/theme_box.html
{% load theme %}
<form method="get" action="{% url 'change_theme' %}">
    {{t_form}}
    <input type="submit" class="button {{user|theme}}" value="Change theme">
</form>