blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("post.urls", namespace="post")),
    path("comment/", include("comment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("categories/", views.category_list, name="categories_list"),
    path("categories/<slug:slug>/", views.category_posts, name="category_posts"),
    path("categories/<str:category>/<slug:slug>/", views.detail, name="detail"),
    path("categories/<str:category>/<slug:slug>/edit/", views.edit, name="edit"),
    path("categories/<str:category>/<slug:slug>/delete/", views.delete, name="delete"),

    path("like/", views.like, name="like"),
    path("new_post/", views.new_post, name="new_post"),
]

templates/base.html
{% load static theme full_name %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9fea9eab69.js" crossorigin="anonymous"></script>
    <title>Index</title>
</head>

<body>
    
    <nav class="navbar {{user|theme}}" role="navigation">
        <div class="navbar-brand">
            <p class="navbar-item title is-3"><span class="icon"><i class="fa-solid fa-hashtag"></i></span></p>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">

                <a href="{% url 'post:index' %}" class="navbar-item p-2">Home</a>
                <a href="{% url 'post:categories_list' %}" class="navbar-item p-2">Categories</a>
            </div>
            <div class="navbar-end">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="navbar-item">Log out</a>
                <a href="{% url 'dashboard' %}" class="navbar-item dashboard">
                    {{user|fullname}}
                    {% if request.user.profile.photo %}
                    <div>
                        <img src="{{user.profile.photo.url}}" alt="{{user}}" class="avatar" />
                    </div>
                    {% else %}
                    <span class="icon"><i class="fa-solid fa-user"></i></span>
                    {% endif %}
                </a>
                <span class="navbar-item has-text-muted">|</span>
                <a href="{% url 'post:new_post' %}" class="navbar-item is-danger">
                    <span>Write a new post</span>
                </a>
                {% else %}
                <a href="{% url 'login' %}" class="navbar-item">Log in</a>
                <a href="{% url 'register' %}" class="navbar-item">Sign up</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% block header %}{% endblock header %}
        {% block content %}{% endblock content %}
        {% block detail %}{% endblock detail %}
    </div>
    <footer class="footer">
        <div class="content has-text-centered">
            <p><strong>Nima Parandavar</strong></p>
            <p><a href="https://www.instagram.com/nima.parandavar/" class="is-link"><span><i class="fa-brands fa-instagram"></i></span> nima.parandavar </a></p>
            <p><a href="https://github.com/nima-parandavar" class="is-link"><span><i class="fa-brands fa-git-square"></i></span> nima-parandavar </a></p>
            <p><a href="https://www.linkedin.com/in/nima-p-753b97138/" class="is-link"><span><i class="fa-brands fa-linkedin"></i></span> nima-p-753b97138</a></p>

        </div>
    </footer>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    {% block script %}{% endblock script %}
</body>

</html>