blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("post.urls", namespace="post")),
    path("comment/", include("comment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from . import views

app_name = "comment"
urlpatterns = [path("send/", views.send, name="send")]

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("categories/", views.category_list, name="categories_list"),
    path("categories/<slug:slug>/", views.category_posts, name="category_posts"),
    path("categories/<str:category>/<slug:slug>/", views.detail, name="detail"),
    path("categories/<str:category>/<slug:slug>/edit/", views.edit, name="edit"),
    path("categories/<str:category>/<slug:slug>/delete/", views.delete, name="delete"),

    path("like/", views.like, name="like"),
    path("new_post/", views.new_post, name="new_post"),
]

post/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from tagging.fields import TagField
from django.db.models.signals import m2m_changed
from django.dispatch import receiver


# create your manager here


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True, category__available=True)


class CategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(available=True)


# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    available = models.BooleanField(default=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE, "posts")
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    banner = models.ImageField(blank=True, upload_to="posts/%Y/%m/%d/")
    tags = TagField(blank=True)
    

    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="categories"
    )
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, "likes", blank=True)
    likes = models.PositiveIntegerField(default=0)

    # managers
    objects = models.Manager()
    available_posts = PostManager()

    def get_absolute_url(self):
        return reverse(
            "post:detail", kwargs={"category": self.category, "slug": self.slug}
        )

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title


# signals
@receiver(m2m_changed, sender=Post.users_like.through)
def like_counter(sender, **kwargs):
    instance: Post = kwargs.get("instance", None)
    action = kwargs.get("action", None)
    if action == "post_add":
        instance.likes += 1
        instance.save()
    elif action == "post_remove":
        instance.likes -= 1
        instance.save()

post/forms.py
from django import forms
from .models import Post
from django.utils.text import slugify
from django.contrib.auth.models import User


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "banner", "tags", "body", "published", "category"]
        field_classes = {
            "banner": forms.ImageField,
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "block input"}),
            "banner": forms.FileInput(attrs={"class": "block"}),
            "tags": forms.TextInput(attrs={"class": "block input"}),
            "published": forms.CheckboxInput(attrs={"class": "block"}),
            "category": forms.Select(attrs={"class": "block input"}),
            "body": forms.Textarea(attrs={"class": "block input"}),
        }

    def save(self, commit: bool = True, user: User = None):
        if user is None:
            raise User.DoesNotExist()

        post: Post = super().save(commit=False)
        title = post.title
        slug = slugify(title)
        post.slug = slug
        post.user = user

        if commit:
            post.save()
        return post


class EditPostForm(NewPostForm):
    pass

post/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse
from .models import Post, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger
from tagging.models import Tag
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import NewPostForm, EditPostForm
from django.contrib.messages import add_message, SUCCESS, ERROR
from comment.forms import CommentForm
from comment.models import Comment

# Create your views here.


def index(request: HttpRequest):
    categories = Category.objects.all()
    tags = Tag.objects.all()

    all_posts = Post.available_posts.all()
    paginator = Paginator(all_posts, 4)
    page = request.GET.get("page", 1)

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage, PageNotAnInteger):
        posts = paginator.page(1)

    context = {"posts": posts, "categories": categories, "tags": tags}
    return render(request, "post/index.html", context)


def category_list(request: HttpRequest):
    categories = Category.objects.all()
    context = {"categories": categories}
    return render(request, "post/categories_list.html", context)


def category_posts(request: HttpRequest, slug):
    posts = Post.available_posts.filter(category__slug=slug)
    category_name = Category.objects.get(slug=slug)
    context = {"posts": posts, "category_name": category_name}
    return render(request, "post/category_posts.html", context)


def detail(request: HttpRequest, category=None, slug=None):
    comment_form = CommentForm()
    action = None
    post = get_object_or_404(Post, category__title=category, slug=slug)
    comments = Comment.objects.filter(post__id = post.id)
    ids = post.users_like.values_list('id', flat=True)
    if request.user.id in ids:
        action = 'dislike'
    else:
        action = 'like'

    context = {"post": post, 'action': action, 'form': comment_form, 'comments': comments}
    return render(request, "post/detail.html", context)


@login_required
def new_post(request: HttpRequest):
    if request.method == "POST":
        form = NewPostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post: Post = form.save(commit=True, user=request.user)
            add_message(
                request,
                SUCCESS,
                f"Post '{post.title}' added",
                "notification is-success",
                False,
            )
            return redirect("dashboard")
    else:
        form = NewPostForm()
    return render(request, "post/new_post.html", {"form": form})

def like(request: HttpRequest):
    if request.user.is_authenticated:
        if request.method == "POST":
            post_id = int(request.POST.get("post_id"))
            post = Post.available_posts.get(id=post_id)
            ids = request.user.likes.values_list("id", flat=True)

            if post_id in ids:
                post.users_like.remove(request.user)
                return JsonResponse(data={"action": "dislike"}, status=200)
            else:
                post.users_like.add(request.user)
                return JsonResponse(data={"action": "like"}, status=200)
    return JsonResponse(data={'action': 'login'}, status=403)



@login_required
def edit(request: HttpRequest, category, slug):
    post = Post.objects.get(category__title=category, slug=slug)
    if request.method == "POST":
        form = EditPostForm(instance=post, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save(commit=True, user=request.user)
            add_message(
                request,
                SUCCESS,
                f"Post '{post.title}' updated",
                "notification is-success",
                False,
            )
            return redirect("dashboard")
    else:
        form = EditPostForm(instance=post)
    return render(request, "post/edit_post.html", {"form": form})


def delete(request: HttpRequest, category, slug):
    post = get_object_or_404(Post, category__title=category, slug=slug)
    post.delete()
    add_message(
                request,
                ERROR,
                f"Post '{post.title}' Deleted",
                "notification is-danger",
                False,
            )
    return redirect('dashboard')

templates/post/categories_list.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="title is-1">Categories</h1>
{% endblock header %}

{% block content %}
    <ul class ="block">
        {% for category in categories %}
            <li class="block">
                <a href="{% url 'post:category_posts' category.slug %}" class="is-large is-link">{{category.title}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/post/category_posts.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="title is-1">{{category_name}}</h1>
{% endblock header %}

{% block content %}
    {% for post in posts %}
        {% include 'partials/my_post_card.html' %}
    {% endfor %}
{% endblock content %}

templates/post/detail.html
{% extends 'base.html' %}
{% load theme %}

{% block detail %}
<div class="column is-6 head">
    {% include 'partials/detail_content.html' %}
    <hr>
    <h3 class="title is-3">Comments</h3>
    <form class="field" action="{% url 'comment:send' %}" method="post" id="commentForm">
        {% csrf_token %}
        <input type="hidden" name="post_id", value="{{post.id}}"/>
        <div class="control block">
            {{form}}
        </div>
        <div class="control block">
            <input type="submit" class="button is-light" value="send">
        </div>
    </form>
    <div class="comments" >
        <ui id="comments">
            {% for comment in comments %}
                {% include 'partials/comment.html' %}
            {% empty %}
                No comment
            {% endfor %}
        </ui>
    </div>
</div>
{% endblock detail %}

{% block script %}
<script>
    $('document').ready(function(){
        $('#likeForm').submit(function(event){
            event.preventDefault()
            var data = $(this).serialize()
            var method = $(this).attr('method')
            var url = $(this).data('url')
            $.ajax({
                method: method,
                url: url,
                data: data,
                type: 'json',
                success: function(response){
                    var counter = $("#likes").text()
                    var likeBtn = $("#likeBtn")
                    if (response['action'] === 'like'){
                        counter++;
                        $("#likes").text(counter)
                        likeBtn.css('color', 'red')
                    }else if (response['action'] === 'dislike'){
                        counter--;
                        $("#likes").text(counter)
                        likeBtn.css('color', 'black')
                    }
                },
                error: function(response){
                    if (response.status === 403){
                        alert("You need to login")
                    }
                }
            })
        })
    })
</script>
{% endblock script %}

templates/post/edit_post.html
{% extends 'base.html' %}

{% block header %}
<h1 class="title is-1">Edit Post</h1>
{% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="{{message.extra_tags}}">{{message}}</div>
{% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_table}}
  <div class="block"><input type="submit" value="Send" class="button is-medium is-light"></div>
</form>
{% endblock content %}

templates/post/index.html
{% extends 'base.html' %}
{% load static theme full_name %}

{% block content %}
    <div class="columns">
        <div class="column is-8 {{user|theme}}">
            {% for post in posts %}
            <div class="card card-display">
                <div class="card-image image imagesize">
                    {% if post.banner %}
                        <img src="{{post.banner.url}}" alt="Image" style="height: 16rem;">
                    {% else %}
                        <img src="{% static 'no_image.PNG' %}" alt="Image" style="height: 16rem;">
                    {% endif %}
                </div>
                <div class="card-top">
                    <div class="card-content">
                        <h3 class="title is-3">{{post.title|capfirst}}</h3>
                        <div class="subtitle is-6 {{user|theme}}">
                            <span class="icon"><i class="fa-solid fa-user"></i></span>
                            <span>{{post.user|fullname}}</span>
                            <span> | </span>
                            <span>{{post.created|timesince}} ago</span>
                        </div>
                        <div class="text content">
                            <p>{{post.body|truncatewords:10|safe}}</p>
                        </div>
                        <div>
                            <a href="{{post.get_absolute_url}}" class="button {{user|theme}} card-item see-more">see more</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% include 'partials/paginator.html' %}
        </div>
        <div class="column">
            {% include 'partials/categories_box.html' %}
            <br>
            {% include 'partials/tags_box.html' %}
        </div>
    </div>
    
{% endblock content %}

templates/post/new_post.html
{% extends 'base.html' %}

{% block header %}
<h1 class="title is-1">New Post</h1>
{% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="{{message.extra_tags}}">{{message}}</div>
{% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_table}}
  <div class="block"><input type="submit" value="Send" class="button is-medium is-light"></div>
</form>
{% endblock content %}